/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleAccount;
import Account.AccountDetail_Bean;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author sriir
 */
public class AccountForm extends javax.swing.JFrame {
    private AccountDetail_Bean accounts;

    /**
     * Creates new form AccountForm
     */
    public AccountForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        GridPanel = new javax.swing.JPanel();
        accountNumberLabel = new javax.swing.JLabel();
        accountNumberInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        balanceLabel = new javax.swing.JLabel();
        balanceInput = new javax.swing.JTextField();
        withdrawAmtLabel = new javax.swing.JLabel();
        withdrawAmtInput = new javax.swing.JTextField();
        currentBalanceLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Manager");

        TitleLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Account Details");

        dateLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Date");

        GridPanel.setLayout(new java.awt.GridLayout(4, 2, 20, 15));

        accountNumberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accountNumberLabel.setText("Account No");
        GridPanel.add(accountNumberLabel);

        accountNumberInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accountNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberInputActionPerformed(evt);
            }
        });
        GridPanel.add(accountNumberInput);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Name");
        GridPanel.add(nameLabel);

        nameInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GridPanel.add(nameInput);

        balanceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceLabel.setText("Balance");
        GridPanel.add(balanceLabel);

        balanceInput.setEditable(false);
        balanceInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GridPanel.add(balanceInput);

        withdrawAmtLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        withdrawAmtLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        withdrawAmtLabel.setText("Enter Amount to Widthdarw");
        GridPanel.add(withdrawAmtLabel);

        withdrawAmtInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GridPanel.add(withdrawAmtInput);

        currentBalanceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        currentBalanceLabel.setText("Current Balance is : ");

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Message");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(currentBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(currentBalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberInputActionPerformed

    }//GEN-LAST:event_accountNumberInputActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        onMessageBtnClicked();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        onOKBtnClicked();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try { 
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) { 
            ex.printStackTrace(); 
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountForm().setVisible(true);
            }
        });
    }

    
    public void onOKBtnClicked() {
        accounts = new AccountDetail_Bean();
        accounts.setAccountNo(Long.parseLong(accountNumberInput.getText()));
        accounts.setName(nameInput.getText());
        accounts.setWithdrawAmount(Double.parseDouble(withdrawAmtInput.getText()));
        
        balanceInput.setText("" + accounts.getBalanceAmt());
        accounts.generateSystemDate();
        currentBalanceLabel.setText("Current Balance :" + accounts.currentBalance());
        dateLabel.setText("Date: " + accounts.getDate());
    }

    public void onMessageBtnClicked() {
        String msg = "Balance in your Account No: " + accounts.getAccountNo() + " as on " + accounts.getDate() + " is " + accounts.currentBalance();
        JOptionPane.showMessageDialog(null, msg, "SMS", JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GridPanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField accountNumberInput;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JTextField balanceInput;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel currentBalanceLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField withdrawAmtInput;
    private javax.swing.JLabel withdrawAmtLabel;
    // End of variables declaration//GEN-END:variables
}