/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class iptex2_Iptex2 */

#ifndef _Included_iptex2_Iptex2
#define _Included_iptex2_Iptex2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     iptex2_Iptex2
 * Method:    change
 * Signature: (Liptex2/SimpleClass;)V
 */
JNIEXPORT void JNICALL Java_iptex2_Iptex2_change
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
